### ISSUE TITLE
.NET 8 application is failing to deploy on App Engine

### ISSUE THREAD

**Issue by amitkumar3-rategain** [GoogleCloudPlatform/buildpacks#439] opened 2024-08-02 05:57 UTC
**Describe the bug**
An ASP.NET Core (.NET Runtime v8) app that we have deployed thousands of times has suddenly stopped deploying, the build process is failing.

If you have a general question about how to use buildpacks, we encourage you to open a [discussion topic instead](https://github.com/GoogleCloudPlatform/buildpacks/discussions)

**Additional context**
How are you using GCP buildpacks?
- [ ] `pack` and the `gcr.io/buildpacks/builder`
- [ ] Cloud Functions
- [ ] Cloud Run
- [ ] Cloud Build
- [ ] App Engine Standard
- [x] App Engine Flex

**Did this used to work?**
*(Yes/No)*

Yes, last deploy worked 19th July

**What language is your project primarily written in?**
*(Python/Java/Node.js/Go/etc.)*

ASP.NET Core (.NET Runtime v8)

**Steps To Reproduce**
1.  gcloud app deploy

**Expected behavior**
The app to deploy.

**Actual behavior**
ERROR: No buildpack groups passed detection.
ERROR: Please check that you are running against the correct path.
ERROR: failed to detect: no buildpacks participating

If applicable, add screenshots / logs / error messages

```
Already have image (with digest): us.gcr.io/serverless-runtimes/google-22-full/builder/dotnet:dotnet_20240722_RC00
Warning: No cached data will be used, no cache specified.
===> ANALYZING
Timer: Analyzer started at 2024-07-25T06:59:54Z
Image with name "us.gcr.io/hosting-rategain/appengine/car-analyticsapi-qaa.20240725t065923:4d0958d9-e17a-4999-9279-8a2560309235" not found
Timer: Analyzer ran for 1.282031794s and ended at 2024-07-25T06:59:56Z
===> DETECTING
Timer: Detector started at 2024-07-25T06:59:56Z
======== Output: google.config.flex@0.9.1 ========
Opting in: X_GOOGLE_TARGET_PLATFORM set to "flex"
======== Output: google.dotnet.flex@0.9.0 ========
Opting in: this is a GAE Flex app.
======== Output: google.dotnet.sdk@0.9.1 ========
Opting in: GOOGLE_RUNTIME  matches "dotnet"
======== Output: google.dotnet.publish@0.9.0 ========
Opting out: no project files found and GOOGLE_BUILDABLE not set
======== Output: google.dotnet.runtime@0.9.1 ========
Opting in: GOOGLE_RUNTIME  matches "dotnet"
======== Output: google.utils.label-image@0.0.2 ========
Opting in: always enabled
======== Results ========
pass: google.config.flex@0.9.1
pass: google.dotnet.flex@0.9.0
pass: google.dotnet.sdk@0.9.1
fail: google.dotnet.publish@0.9.0
pass: google.dotnet.runtime@0.9.1
pass: google.utils.label-image@0.0.2
======== Output: google.dotnet.sdk@0.9.1 ========
Opting in: GOOGLE_RUNTIME  matches "dotnet"
======== Output: google.dotnet.appengine-main@0.9.0 ========
Opting out: X_GOOGLE_TARGET_PLATFORM not set to "gae"
======== Output: google.dotnet.publish@0.9.0 ========
Opting out: no project files found and GOOGLE_BUILDABLE not set
======== Output: google.dotnet.runtime@0.9.1 ========
Opting in: GOOGLE_RUNTIME  matches "dotnet"
======== Output: google.dotnet.appengine@0.9.0 ========
Opting out: X_GOOGLE_TARGET_PLATFORM not set to "gae"
======== Output: google.utils.label-image@0.0.2 ========
Opting in: always enabled
======== Results ========
pass: google.dotnet.sdk@0.9.1
skip: google.dotnet.appengine-main@0.9.0
skip: google.dotnet.publish@0.9.0
pass: google.dotnet.runtime@0.9.1
fail: google.dotnet.appengine@0.9.0
pass: google.utils.label-image@0.0.2
======== Output: google.dotnet.sdk@0.9.1 ========
Opting in: GOOGLE_RUNTIME  matches "dotnet"
======== Output: google.utils.archive-source@0.0.1 ========
Opting out: Env var X_GOOGLE_TARGET_PLATFORM is not set to gcf.
======== Output: google.dotnet.functions-framework@0.0.1 ========
Opting out: GOOGLE_FUNCTION_TARGET not set
======== Output: google.dotnet.publish@0.9.0 ========
Opting out: no project files found and GOOGLE_BUILDABLE not set
======== Output: google.dotnet.runtime@0.9.1 ========
Opting in: GOOGLE_RUNTIME  matches "dotnet"
======== Output: google.utils.label-image@0.0.2 ========
Opting in: always enabled
======== Results ========
pass: google.dotnet.sdk@0.9.1
skip: google.utils.archive-source@0.0.1
fail: google.dotnet.functions-framework@0.0.1
fail: google.dotnet.publish@0.9.0
pass: google.dotnet.runtime@0.9.1
pass: google.utils.label-image@0.0.2
======== Output: google.dotnet.sdk@0.9.1 ========
Opting in: GOOGLE_RUNTIME  matches "dotnet"
======== Output: google.dotnet.functions-framework@0.0.1 ========
Opting out: GOOGLE_FUNCTION_TARGET not set
======== Output: google.dotnet.publish@0.9.0 ========
Opting out: no project files found and GOOGLE_BUILDABLE not set
======== Output: google.dotnet.runtime@0.9.1 ========
Opting in: GOOGLE_RUNTIME  matches "dotnet"
======== Output: google.config.entrypoint@0.9.0 ========
Opting out: GOOGLE_ENTRYPOINT not set, no valid entrypoint in app.yaml and Procfile not found
======== Output: google.utils.label-image@0.0.2 ========
Opting in: always enabled
======== Results ========
pass: google.dotnet.sdk@0.9.1
skip: google.dotnet.functions-framework@0.0.1
fail: google.dotnet.publish@0.9.0
pass: google.dotnet.runtime@0.9.1
skip: google.config.entrypoint@0.9.0
pass: google.utils.label-image@0.0.2
======== Output: google.dotnet.runtime@0.9.1 ========
Opting in: GOOGLE_RUNTIME  matches "dotnet"
======== Output: google.config.entrypoint@0.9.0 ========
Opting out: GOOGLE_ENTRYPOINT not set, no valid entrypoint in app.yaml and Procfile not found
======== Output: google.utils.label-image@0.0.2 ========
Opting in: always enabled
======== Results ========
pass: google.dotnet.runtime@0.9.1
fail: google.config.entrypoint@0.9.0
pass: google.utils.label-image@0.0.2
Timer: Detector ran for 148.328554ms and ended at 2024-07-25T06:59:56Z
ERROR: No buildpack groups passed detection.
ERROR: Please check that you are running against the correct path.
ERROR: failed to detect: no buildpacks participating. ```

**Comment by kennethye1** [comment] 2024-08-20 21:58
Duplicate of https://github.com/GoogleCloudPlatform/buildpacks/issues/432

**Closed** 2024-08-20 21:57 UTC
Labels: kind/bug
