### ISSUE TITLE
Python runtimes are not found on dl.google.com?

### ISSUE THREAD

**Issue by manojlds** [GoogleCloudPlatform/buildpacks#199] opened 2022-04-22 06:18 UTC
On v0.24.1, and I am getting this error:

```
=== Python - Runtime (google.python.runtime@0.9.1) ===
Using Python version from .python-version: 3.7.9
Installing Python v3.7.9.
2022/04/22 05:55:48 [DEBUG] GET https://dl.google.com/runtimes/python/python-3.7.9.tar.gz
WARNING: Failed to download Python version 3.7.9. You can specify the verison by setting the GOOGLE_RUNTIME_VERSION environment variable
Failure: (ID: f0be19f7) fetching https://dl.google.com/runtimes/python/python-3.7.9.tar.gz returned HTTP status: 404
```

The URL is giving 404 and I am not sure what should be fixed here.

**Comment by grant** [comment] 2022-04-26 19:20
Can you provide more details for your configuration? You need to provide the UA.

```
curl -A GCPBuildpacks https://dl.google.com/runtimes/python/python-3.7.0.tar.gz -O
```

Closing due to not enough detail and workaround.

**Comment by matthewrobertson** [comment] 2022-04-26 19:23
I think the problem is the only version of python3.7 in the versions manifest is 3.7.12:

```
curl -A GCPBuildpacks https://dl.google.com/runtimes/python/version.json
["3.10.0","3.10.1","3.10.2","3.7.12","3.8.0","3.8.1","3.8.10","3.8.11","3.8.12","3.8.13","3.8.2","3.8.3","3.8.4","3.8.5","3.8.6","3.8.7","3.8.8","3.8.9","3.9.0","3.9.1","3.9.10","3.9.11","3.9.12","3.9.2","3.9.3","3.9.4","3.9.5","3.9.6","3.9.7","3.9.8","3.9.9"]
```

**Comment by grant** [comment] 2022-04-26 19:25
> We should backfill all python3.7 versions

Sounds good.

**Comment by pcperera** [comment] 2022-04-28 07:08
I receive a similar error.

`
===> BUILDING
[builder] === Python - Runtime (google.python.runtime@0.9.1) ===
[builder] Using Python version from GOOGLE_RUNTIME_VERSION: 3.8.10
[builder] Installing Python v3.8.10.
[builder] 2022/04/28 06:54:01 [DEBUG] GET https://dl.google.com/runtimes/python/python-3.8.10.tar.gz
[builder] WARNING: Failed to download Python version 3.8.10. You can specify the verison by setting the GOOGLE_RUNTIME_VERSION environment variable
[builder] Failure: (ID: 3d02a68a) symlinking "/layers/google.python.runtime/python/bin/pydoc3" to "pydoc3.8": symlink pydoc3.8 /layers/google.python.runtime/python/bin/pydoc3: file exists
`

**Comment by matthewrobertson** [comment] 2022-04-28 07:23
@pcperera that sounds like an error extracting the tar file. I will investigate, for now you might try to use a different version of Python (eg 3.8.13). You can pass it in the `GOOGLE_RUNTIME_VERSION` env var or in a `.python-version` file in the root of your project.

**Comment by matthewrobertson** [comment] 2022-04-28 07:25
@manojlds you should be able to work around by updating your `.python-version` file to use `3.7.12`. We are working on backfilling the other versions but it will take some time.

**Comment by pcperera** [comment] 2022-04-28 07:38
@matthewrobertson 
I do seem to get the same error for 3.8.13 too.

`
===> BUILDING
[builder] === Python - Runtime (google.python.runtime@0.9.1) ===
[builder] Using Python version from GOOGLE_RUNTIME_VERSION: 3.8.13
[builder] Installing Python v3.8.13.
[builder] 2022/04/28 07:37:40 [DEBUG] GET https://dl.google.com/runtimes/python/python-3.8.13.tar.gz
[builder] WARNING: Failed to download Python version 3.8.13. You can specify the verison by setting the GOOGLE_RUNTIME_VERSION environment variable
[builder] Failure: (ID: 3d02a68a) symlinking "/layers/google.python.runtime/python/bin/pydoc3" to "pydoc3.8": symlink pydoc3.8 /layers/google.python.runtime/python/bin/pydoc3: file exists
[builder] --------------------------------------------------------------------------------
`

**Comment by matthewrobertson** [comment] 2022-04-28 07:55
@pcperera how are you running the buildpacks? Is this happening on your local machine or in CloudBuild?

**Comment by pcperera** [comment] 2022-04-28 07:59
@matthewrobertson, locally on minikube with skaffold.

**Comment by 0xhf** [comment] 2022-04-28 08:03
I also had this problem. Updating pack to the latest version fixed it for me.

**Comment by matthewrobertson** [comment] 2022-04-28 08:19
@pcperera I think I understand what is happening here. We aren't clearing the cache layer properly when upgrading to a new Python version in a previously built app. There is a simple fix for this on our end, but it will take some time to get it released in the buildpacks. To work around, you should be able to skip the cache restoration when you build. I am not too familiar with skaffold, but you need to pass the `--clear-cache` flag to the `pack build` command. Alternatively, you might be able to set the `CNB_SKIP_RESTORE=true` build env var.

**Comment by pcperera** [comment] 2022-04-28 09:58
Unfortunately CNB_SKIP_RESTORE didn't quite work. GOOGLE_BUILD_ARGS too not for Python ?

**Comment by matthewrobertson** [comment] 2022-04-28 19:52
@pcperera the fix was landed in https://github.com/GoogleCloudPlatform/buildpacks/commit/5a57252b958d6daef6449e9906bd6a56d05390b6 and should be available in the latest builder. Please let me know if you are still having issues.

**Comment by matthewrobertson** [comment] 2022-04-29 18:06
We have backfilled all versions of python3.7 and released a new builder with a fix for the symlink bug. This issue should be fully resolved now.

**Closed by matthewrobertson** 2022-04-29 18:06 UTC
