### ISSUE TITLE
If Dockerfile is present at the root, perform a regular Docker build

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/buildpacks#62] opened 2020-07-15 21:28 UTC
Today, running `pack build --builder gcr.io/buildpacks/builder` in a repo that contains code written in popular languages will result in a nice container for these languages.
Sadly, if this repo contains a `Dockerfile`, then the command will ignore it and still do a language detection.
This means that developers now have to change their tooling (`pack` vs `docker`) depending on the kind of build they want to perform.

It would be simpler if  `pack build --builder gcr.io/buildpacks/builder` would detect the presence of the `Dockerfile` and trigger a regular docker build if present (taking priority over any other language detection)

This would greatly simplify the onboarding of Cloud Run or setting up Continuous Deployment.

Is it possible to add a Buildpack that performs a simple docker build and update the detection logic of the Builder?

**Comment by jamesward** [comment] 2020-07-15 21:30
I think this is a great idea!

**Comment by squee1945** [comment] 2020-07-15 21:31
Buildpacks, by design, don't have direct access to the Docker daemon in this way. This would have to be implemented by the platform itself (e.g., `pack`).

**Comment by jamesward** [comment] 2020-07-15 21:39
Since the buildpacks run in a container, could that container be one with docker in it?  Is the docker socket mounted in the container when a buildpack runs?

**Comment by squee1945** [comment] 2020-07-15 22:20
The relevant part of the spec is here: https://github.com/buildpacks/spec/blob/main/buildpack.md#assumptions-of-trust

```
Prohibited:

 - The application source code MUST NOT have access to credentials for reading and writing to OCI image stores.
 - Buildpacks MUST NOT have access to credentials for reading and writing to OCI image stores.
```

**Comment by steren** [comment] 2020-07-15 22:32
So, should we suggest this to be added to `pack` itself?

And if not, let's create a new tool named `packer`, that wraps `pack` and `docker` 😄  (half joking)

**Comment by jamesward** [comment] 2020-07-17 14:20
Another option for a dockerfile buildpack would be to use a library that can parse a `Dockerfile` and manually do the assembling.  Jib has implemented some of this. I think there is a go-based docker impl and a Java one.  Caveats would be it may not be 100% compatible with `docker build` but may be sufficiently close.

**Comment by steren** [comment] 2020-07-17 15:23
Maybe https://github.com/GoogleContainerTools/kaniko ?

> kaniko is a tool to build container images from a Dockerfile, inside a container

**Comment by steren** [comment] 2020-07-18 15:52
I suggested this behavior to be added to `pack` https://github.com/buildpacks/pack/issues/756

**Comment by briandealwis** [comment] 2020-12-03 15:24
Closing.  We could maybe create a buildpack that would attempt to interpret a subset of the dockerfile directives, such as running some of the RUN directives, but it would be a poor experience.

**Closed by briandealwis** 2020-12-03 15:24 UTC
