### ISSUE TITLE
yarn 1 no longer working

### ISSUE THREAD

**Issue by modosc** [GoogleCloudPlatform/buildpacks#182] opened 2022-02-16 20:34 UTC
this started sometime in the past few days. all of our node cloudfunction deploys fail 100% of the time now:
```
Step #1 - "build": Adding image label google.source-archive: /workspace/.googlebuild/source-code.tar.gz
Step #1 - "build": === Node.js - Yarn (google.nodejs.yarn@2.0.0) ===
Step #1 - "build": DEBUG: ***** CACHE MISS: "yarn_engine"
Step #1 - "build": Installing Yarn v1
Step #1 - "build": --------------------------------------------------------------------------------
Step #1 - "build": Running "bash -c curl --fail --show-error --silent --location --retry 3 https://yarnpkg.com/downloads/1/yarn-v1.tar.gz | tar xz --directory /layers/google.nodejs.yarn/yarn_engine --strip-components=1"
Step #1 - "build": curl: (22) The requested URL returned error: 404 
Step #1 - "build": gzip: stdin: unexpected end of file
Step #1 - "build": tar: Child returned status 1
Step #1 - "build": tar: Error is not recoverable: exiting now
Step #1 - "build": Done "bash -c curl --fail --show-error --silent --location --retry..." (975.929345ms)
```

**Comment by modosc** [comment] 2022-02-16 20:41
looks like this is the change that broke things:

https://github.com/GoogleCloudPlatform/buildpacks/commit/b42d29a5224a1cfbaa8a3150b37e20e6db6fce86#diff-7f171c37897b2bd5b3bcafe051b07af8bf09746350a61f30a9acf3aef18c0431

**Comment by modosc** [comment] 2022-02-16 20:50
we have this in our `package.json`:
```json
  "engines": {
    "node": "16",
    "yarn": "1"
  },
```

**Comment by matthewrobertson** [comment] 2022-02-16 22:00
Sorry to hear you are having trouble with this. This sounds like a bug in which we are not resolving a valid fully qualified version of yarn from the specifier you provided in your `package.json`. I think you should be able to unblock your deployments by providing a full semver of an existing yarn version. For example:

```
  "engines": {
    "node": "16",
    "yarn": "1.22.17"
  },
```

**Comment by modosc** [comment] 2022-02-16 22:07
thanks @matthewrobertson , we're trying that now.

i think this code would also break for something like `"yarn": "^0.14.0"` which is a [valid example from yarn's docs](https://classic.yarnpkg.com/en/docs/package-json#toc-engines)

**Comment by matthewrobertson** [comment] 2022-02-16 22:57
@modosc I *think* `"yarn": "^0.14.0"` will actually work fine. We should be treating `engines.yarn` as a fuzzy version specifier and using it to resolve a matching available version published to npm. 

My current theory is that the problem is [this early return](https://github.com/GoogleCloudPlatform/buildpacks/blob/0be19970636e19fbe0a9146a5b30f75aa3fa0a91/pkg/nodejs/registry.go#L53-L55). The intention is that we shouldn't need to fetch the list of all versions if you provided an exact semver. Unfortunately, it looks like `version.IsExactSemver("1") == true`, which was an oversight on my part. 

For now you should be able to do something like `"yarn": "1.x.x"` to match the behaviour you had before. I will work on a patch to do the same thing for `"1"`

**Closed** 2022-02-24 03:19 UTC
Labels: kind/bug
