### ISSUE TITLE
Strange Cache Error

### ISSUE THREAD

**Issue by jamesward** [GoogleCloudPlatform/buildpacks#14] opened 2020-05-08 14:50 UTC
```
~/projects/buildpack-samples/sample-python $ pack build sample-python --builder=gcr.io/buildpacks/builder
latest: Pulling from buildpacks/builder
Digest: sha256:680714dad5cb0baa21f388701b8f6d52b0ca5cc4ac56aa5e12c5629c68927d26
Status: Image is up to date for gcr.io/buildpacks/builder:latest
latest: Pulling from buildpacks/gcp/run
Digest: sha256:33ccc0fffbff5fa4085db4cb758ce323c9a717c0d19e5fc38d61cbdb3d10a14b
Status: Image is up to date for gcr.io/buildpacks/gcp/run:latest
===> DETECTING
[detector] google.python.runtime    0.9.0
[detector] google.python.pip        0.9.0
[detector] google.config.entrypoint 0.9.0
===> ANALYZING
[analyzer] ERROR: failed to initialize cache: failed to create volume cache: removing backup directory '/cache/committed-backup': unlinkat /cache/committed-backup/sha256:8572a50f2f8896c81251ab27a1538435066ebe4d40afcd93f7cc2ac92e008a4d.tar: permission denied
ERROR: failed with status code: 1
```

**Comment by lukasberger** [comment] 2020-05-08 16:25
This looks like a lower-level error, either due to pack or Docker. Have you been able to reproduce?

**Comment by jamesward** [comment] 2020-05-08 16:53
Yeah, it might be a pack bug. I tried again with `--clear-cache` and it still failed but on the `exporter` step:
```
[exporter] ERROR: failed to create launch cache: removing backup directory '/launch-cache/committed-backup': unlinkat /launch-cache/committed-backup/sha256:67987cd5dd44347d972912ac043ddb991419130da898318d8f827e737c4104fc.tar: permission denied
```
I can't reproduce outside of my machine.  :(

Giving pack a different image name makes it work (i.e. changing the cache key).

**Comment by lukasberger** [comment] 2020-05-08 19:07
It sounds like the cache was corrupted in some way. You could also clear it with `docker volume prune`.

**Comment by lukasberger** [comment] 2020-05-11 23:09
I am going to close this since it seems unrelated to this project. Please reopen if you find otherwise.

**Closed by lukasberger** 2020-05-11 23:09 UTC
Labels: invalid
