### ISSUE TITLE
PHP composer gcp-build variable not working under standard builder

### ISSUE THREAD

**Issue by sl0wik** [GoogleCloudPlatform/buildpacks#278] opened 2023-02-23 22:02 UTC
`gcp-build` composer handling is not supported while using standard builder.

Regular `pack build service --builder=gcr.io/buildpacks/builder:latest` would result in:
```
===> DETECTING
[detector] 6 of 7 buildpacks participating
[detector] google.php.runtime          0.0.1
[detector] google.utils.nginx          0.0.1
[detector] google.php.composer-install 0.0.1
[detector] google.php.composer         0.9.1
[detector] google.utils.label          0.0.2
[detector] google.php.webconfig        0.0.1
```
(missing `google.php.composer-gcp-build`)

It would work using `pack build service --builder=gcr.io/gae-runtimes/buildpacks/php81/builder:latest --env=X_GOOGLE_TARGET_PLATFORM=gae`.

Result:
```
===> DETECTING
[detector] google.php.composer-install   0.0.1
[detector] google.php.composer-gcp-build 0.9.1
[detector] google.php.composer           0.9.1
[detector] google.php.appengine          0.9.0
[detector] google.utils.label            0.0.2
```

**Comment by jama22** [comment] 2023-02-24 18:04
I believe this is intended behavior. The GAE PHP builder specifically includes GCP and GAE specific buildpacks to help with the developer experience. You can see the full list of included buildpacks in the [builder.toml](https://github.com/GoogleCloudPlatform/buildpacks/tree/main/builders/php)

The generic builder `gcr.io/buildpacks/builder:latest` is designed to build PHP applications that can be built/deployed anywhere, so thats why `gcp-build` isn't included

**Comment by kritkasahni-google** [comment] 2023-02-24 22:40
@sl0wik Thanks for reaching out! You are right at the moment looks like our standard build is not supporting running script titled "gcp-build" specified inside composer.json during /bin/build. Could you provide example of use cases where you think it would required to support gcp-build  for php with standard builder? Also what is your use case here?

**Comment by sl0wik** [comment] 2023-03-15 15:57
Sure. May builds require custom steps like creating a routing cache, or framework bootstrap file. In serverless environment, those files cant be generated on run and need to be generated during the build. You might also need extra steps like running migrations. gcp-build allows adding extra steps while build happen in the cloud (usually for CloudRun or App Engine).

**Comment by sl0wik** [comment] 2023-03-17 20:58
PR https://github.com/GoogleCloudPlatform/buildpacks/pull/283

**Comment by kritkasahni-google** [comment] 2023-04-05 18:24
Commit https://github.com/GoogleCloudPlatform/buildpacks/commit/1b1d9b360bba69c917b60c29c77cc0b563ed9f4e

**Comment by matthewrobertson** [comment] 2023-05-18 04:45
I believe this is fixed now. @sl0wik please re-open if you are still having trouble.

**Closed by matthewrobertson** 2023-05-18 04:45 UTC
Labels: kind/question
