### ISSUE TITLE
Current gcr.io/buildpacks/builder:v1 broken

### ISSUE THREAD

**Issue by DGollings** [GoogleCloudPlatform/buildpacks#170] opened 2022-01-17 14:30 UTC
Surprised nobody has mentioned this, I'm the only person crazy enough not to 'pin' versions? Noticed this a couple days ago:
```
Canceled build for *my image*
validating stack mixins: buildpack 'google.utils.label@0.0.2' does not support stack 'google'
```
Can confirm it occurs for Skaffold 1.34 and 1.35.2

Is this a bug or a feature?

Whilst pondering the above question I built the sample-go app in the readme. It 'builds' (the little there is to build)
(`pack build --builder gcr.io/buildpacks/builder:v1 sample-go`)

So to add more info, I'm running a pretty standard Go(lang) build, apart from settings ENVs 
`GOOGLE_BUILDABLE`
`GOOGLE_CLEAR_SOURCE`
`GOOGLE_DEVMODE`

**Comment by xSAVIKx** [comment] 2022-01-17 15:08
Yeeep, our CI builds are also failing now.

**Comment by DGollings** [comment] 2022-01-17 15:10
@xSAVIKx  my 'fix'
`gcr.io/buildpacks/builder@sha256:386d9463cbab60718d1f9e213df9e3ccf5e166190696be69bdd16d7d466875bd`

(picked a pretty random SHA, but works for me)

**Comment by xSAVIKx** [comment] 2022-01-17 15:11
You can pick some latest one from here as well: https://console.cloud.google.com/gcr/images/buildpacks/GLOBAL/builder

**Comment by xSAVIKx** [comment] 2022-01-17 21:43
@matthewrobertson @MontyCarter do you maybe know what can the the issue here and when this can be addressed?

**Comment by xSAVIKx** [comment] 2022-01-17 21:51
> @xSAVIKx my 'fix' `gcr.io/buildpacks/builder@sha256:386d9463cbab60718d1f9e213df9e3ccf5e166190696be69bdd16d7d466875bd`
> 
> (picked a pretty random SHA, but works for me)

Also, this image fails for me with the following error:
```
Digest: sha256:386d9463cbab60718d1f9e213df9e3ccf5e166190696be69bdd16d7d466875bd
Status: Downloaded newer image for gcr.io/buildpacks/builder:17cbb932fff1a1487d75bfee65c0f0e21a0abc2c
ERROR: failed to build: fetching lifecycle image: resolve auth for ref buildpacksio/lifecycle:0.13.1: error getting credentials - err: exit status 1, out: ``
```

I'm building a container in the local env. Just FYI, I have another build that uses `gcloud builds submit --pack` and that one works fine in the cloud.

I may attempt to move my current build to Cloud Build env and check.

**Comment by matthewrobertson** [comment] 2022-01-18 02:20
Sounds like this is a regression caused by the update to use wildcard stacks in: https://github.com/GoogleCloudPlatform/buildpacks/commit/3ce58348bc60686a2a2051cc438ac59350ee4ced

Sorry for the inconvenience. I am not able to reproduce the issue on my end. I suspect it is caused by some conflicting version of pack that doesn't support wildcard stacks.

@xSAVIKx  or @DGollings could you tell me more about how your are building your applications? If possible could you share a cloudbuild config that reproduces the error?

**Comment by matthewrobertson** [comment] 2022-01-18 02:38
@briandealwis maybe you have more info about what could be happening here? Is skaffold using an old version of pack?

**Comment by matthewrobertson** [comment] 2022-01-18 06:09
I landed a commit to revert what I suspect to be the offending change. It will take a few hours for the CI to publish a new builder.

**Comment by xSAVIKx** [comment] 2022-01-18 08:43
I can confirm that the bc039ad change fixes the builder (resulted in the new builder image: https://console.cloud.google.com/gcr/images/buildpacks/global/builder@sha256:4a9460c52d511b306acdd5a939c5607f08654750fd4c10e00a5fad296b4eccd2/details) 


I basically have a `pack` build running in GitHub Actions environment, smth like:
```shell
export GCP_PROJECT="${GCP_PROJECT}"
export IMAGE_NAME="gcr.io/${GCP_PROJECT}/<image-name>"

GITHUB_SHA=$( git rev-parse HEAD )
BUILDER_IMAGE_NAME="gcr.io/buildpacks/builder:v1"
RUNTIME_IMAGE_NAME="gcr.io/${GCP_PROJECT}/<runtime-image-name>"
IMAGE_VERSION="0.0.1"
pack build "${IMAGE_NAME}" \
  --builder "${BUILDER_IMAGE_NAME}" \
  --run-image "${RUNTIME_IMAGE_NAME}" \
  --tag "${IMAGE_NAME}:latest" \
  --tag "${IMAGE_NAME}:${GITHUB_SHA}" \
  --tag "${IMAGE_NAME}:${GITHUB_SHA:0:7}" \
  --tag "${IMAGE_NAME}:v${IMAGE_VERSION}" \
  --publish
```

And this setup builds a Python application based on Functions Framework.

**Comment by DGollings** [comment] 2022-01-18 10:27
@matthewrobertson 

Good news, I can reproduce. Normally I build and deploy everything with Skaffold, but sometimes I do a hotfix using a simple CLI oneliner

Using image `gcr.io/buildpacks/builder@sha256:4d69800df46491214311eb590a3a213e02d6e04fafd26232067afc4a0943e749`

This works (identical to Skaffold)
```
export SERVICENAME=foo;export TAG=$(date +%s); pack build eu.gcr.io/our-shield-303914/${${SERVICENAME}}-go:$TAG  --builder gcr.io/buildpacks/builder@sha256:4d69800df46491214311eb590a3a213e02d6e04fafd26232067afc4a0943e749 --env=GOOGLE_BUILDABLE="./api/${${SERVICENAME}}/cmd/${${SERVICENAME}}" --env=GOOGLE_CLEAR_SOURCE=true --env=GOOGLE_DEVMODE=true
```

But, I checked the Skaffold go.mod and they use version 0.18  

Downloaded 0.18 manually, ran the exact some command (against the old binary of course)  
```
❯ export SERVICENAME=foo;export TAG=$(date +%s); ./pack build eu.gcr.io/our-shield-303914/${${SERVICENAME}}-go:$TAG  --builder gcr.io/buildpacks/builder@sha256:4d69800df46491214311eb590a3a213e02d6e04fafd26232067afc4a0943e749 --env=GOOGLE_BUILDABLE="./api/${${SERVICENAME}}/cmd/${${SERVICENAME}}" --env=GOOGLE_CLEAR_SOURCE=true --env=GOOGLE_DEVMODE=true
```
results in
```
gcr.io/buildpacks/builder@sha256:4d69800df46491214311eb590a3a213e02d6e04fafd26232067afc4a0943e749: Pulling from buildpacks/builder
Digest: sha256:4d69800df46491214311eb590a3a213e02d6e04fafd26232067afc4a0943e749
Status: Image is up to date for gcr.io/buildpacks/builder@sha256:4d69800df46491214311eb590a3a213e02d6e04fafd26232067afc4a0943e749
v1: Pulling from buildpacks/gcp/run
Digest: sha256:1004d44153a76910b05f9bc060682172452ffc05eee1331aeb69e03e3a9f01ea
Status: Image is up to date for gcr.io/buildpacks/gcp/run:v1
ERROR: failed to build: validating stack mixins: buildpack google.utils.label@0.0.2 does not support stack google
❯ ./pack version
0.18.0+git-e00ee4a.build-2328
```

:)

**Comment by briandealwis** [comment] 2022-01-19 13:48
Sorry I have a patch for Skaffold to update to a later version of pack-as-a- library. I’ll try to get that in ASAP.

**Comment by matthewrobertson** [comment] 2022-01-20 19:28
I think most open source customers will be using the buildpacks with the google stack so we can keep that one in the toml files and add the wildcard for the product specific ones.

**Closed** 2022-01-28 20:08 UTC

**Comment by briandealwis** [comment] 2022-01-28 20:10
It's committed to HEAD (https://github.com/GoogleContainerTools/skaffold/pull/6979) and will be in the next release.  Anybody needing this now can use the "bleeding edge" binaries from https://skaffold.dev/docs/install
