### ISSUE TITLE
Detecting my app as PHP instead of Node

### ISSUE THREAD

**Issue by philipwigg** [GoogleCloudPlatform/buildpacks#220] opened 2022-07-20 10:21 UTC
### Summary

Build packs seem to be detecting my application as a PHP app when it's a NodeJS application.

I'm deploying a NodeJS Cloud Run application from source. To deploy it, I use:-

```
gcloud run deploy my-app-nane \
  --source . \
  --project my-project \
  --platform managed \
  --allow-unauthenticated \
  --region europe-west2
```

It's been working fine for months. I've only made minor changes to the code.

However, build packs seem to be detecting my node application as a PHP app and not Node anymore and my app fails with FastCGI errors (which I should not have installed).

See the comparison (today vs about 11 days ago)

![nodephp](https://user-images.githubusercontent.com/244059/179959125-11ba4cf0-87ae-4ba5-b2b2-43862a0c2c76.png)

---

##### Steps
I'm not sure how you can reproduce this without handing over my source code, but this must be happening to others?

**Comment by philipwigg** [comment] 2022-07-20 10:52
So it seems like I had installed `eslint` installed, which had a dependency called `flatten`, which contains a .PHP file. When I removed this, it went back to being detected as Node again.

**Comment by philipwigg** [comment] 2022-07-20 11:15
I'm reopening to ask, is this the desired behaviour? Should a single .php file in the repo override the fact I have 99.9% .js files and a package.json?

**Comment by spew** [comment] 2022-07-20 14:15
This is not desired behavior and represents how our detection logic needs to become more robust.

**Comment by philipwigg** [comment] 2022-07-20 14:21
Since I've had `eslint` installed for ages and I only just saw this issue, I wonder if https://github.com/GoogleCloudPlatform/buildpacks/commit/d34b0c51706cbb40761bf77bdec82d6c83f23d01 caused my particular issue?

**Comment by philipwigg** [comment] 2022-07-20 14:23
I'm adding the "primary script unknown" error I received in Cloud Run, just in case anyone else has the same problem and Google can send them here.

```2022-07-20 00:29:47.120 BST2022/07/19 23:29:47 [error] 33#33: *7 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 169.254.1.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/layers/google.php.webconfig/webconfig/app.sock:", host: "my-app-url", referrer: "https://console.cloud.google.com/"```

**Comment by ace-n** [comment] 2022-07-29 17:45
As a hotfix - would it be bad to ignore "dependency directories" in the runtime detection logic?

e.g. ignoring `composer` or `node_modules` seems like a reasonably-safe compromise to me provided we document it.

**Comment by matthewrobertson** [comment] 2022-07-29 19:04
This is an issue we encountered in the past. Unfortunately, we have to impose some prioritized language detection order. We pushed nodejs to the bottom because it is very common to get false positives for node (eg it is very common for python websites to include some js files).

> Strangely, specifying `GOOGLE_RUNTIME` doesn't appear to fix this. (We should prioritize explicit user-specified values over implicit automatically-determined ones.)

That is definitely a bug and we should push a fix ASAP.

**Comment by matthewrobertson** [comment] 2022-07-29 19:11
I just looked at the code and it seems like setting the build env var `GOOGLE_RUNTIME=nodejs` should fix this. @ace-n how did you try set it? On cloud run the only way to set build env vars is to create a `project.toml` file in the root. In this case the content should be like:

```
[[build.env]]
name = "GOOGLE_RUNTIME"
value = "nodejs"
```

@philipwigg could you try and create a `project.toml` as I described above as a workaround?

**Comment by matthewrobertson** [comment] 2022-07-29 19:16
Also, @philipwigg if I am reading the description of your issue correctly, it sounds like the `.php` file is in your `node_modules` directory. I would recommend you ignore that dir entirely when deploying to cloud run. The buildpacks will delete it and re-install the modules anyway, so including it will only slow your build down.

Docs explaining how to to ignore files using a `.gcloudignore` are here: https://cloud.google.com/sdk/gcloud/reference/topic/gcloudignore

**Comment by ace-n** [comment] 2022-07-29 19:54
@matthewrobertson I tried setting the `GOOGLE_RUNTIME` variable via Cloud Build configs:
```
env:
  - GOOGLE_RUNTIME: 'nodejs'
```

I confirmed that it showed up in the Cloud Build UI, too.

**Comment by matthewrobertson** [comment] 2022-07-30 01:02
> can we have a "deny-list" of folders we ignore when determining dependencies? Ignoring directories like node_modules seems like a straightforward enough solution to me.

That is a good idea, that shouldn't be too hard to implement

**Comment by ace-n** [comment] 2022-07-30 18:40
Some sleuthing:
- [This](https://github.com/GoogleCloudPlatform/buildpacks/blob/62db16418049fa9835a84e18f312b11bb7c6d488/cmd/php/runtime/main.go#L51) looks like the file that's "finding" erroneous PHP files
- The [`hasAtLeastOne` function](https://github.com/GoogleCloudPlatform/buildpacks/blob/84224760cde67a43f800e7671c6874344cf1be81/pkg/gcpbuildpack/filepath.go#L35) is likely what we need to change, specifically [this section](https://github.com/GoogleCloudPlatform/buildpacks/blob/84224760cde67a43f800e7671c6874344cf1be81/pkg/gcpbuildpack/filepath.go#L47)

I'll see if I can't take a look at this on Monday. 🙂

**Comment by ace-n** [comment] 2022-08-02 23:58
Hi @philipwigg,

Thanks again for filing this issue!

I've submitted a fix for this internally; @spew and @matthewrobertson are working on reviewing it. ✨

That said - we'll keep this issue open until the fix has been merged. ✅

**Comment by ace-n** [comment] 2022-08-08 19:05
Fix merged! I'll double check with @spew that we can close this issue. 🙂

**Closed** 2022-08-08 20:12 UTC
Labels: kind/bug, kind/enhancement, good first issue
