### ISSUE TITLE
Node: failed dependency install is ignored

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/buildpacks#96] opened 2020-12-16 20:39 UTC
Minimal repro: https://github.com/ahmetb/tfjs-cloudrun/tree/e47b2a9

This app works fine locally. 

However while it's building on GCB, installing `@tensorflow/tfjs-node` dep fails, **but this is ignored**, leading to random module to be "not found" during execution.

package.json:

```
{
  "name": "object-detection",
  "scripts": {
    "start": "node index.js"
  },
  "engines": {
    "node": "14"
  },
  "main": "index.js",
  "dependencies": {
    "@tensorflow/tfjs-node": "^1.4.0",
    "busboy": "^0.3.1",
    "express": "^4.17.1"
  }
}
```

relevant error log stmts from `pack`:

```
===> BUILDING
=== Node.js - Runtime (google.nodejs.runtime@0.9.2) ===
Resolving Node.js version based on semver "14"
--------------------------------------------------------------------------------
Running "curl --fail --show-error --silent --location --get --data-urlencode range=14 http://semver.io/node/resolve"
14.15.2Done "curl --fail --show-error --silent --location --get --data-ur..." (410.123185ms)
Using resolved runtime version from package.json: 14.15.2
Installing Node.js v14.15.2
--------------------------------------------------------------------------------
Running "bash -c curl --fail --show-error --silent --location --retry 3 https://nodejs.org/dist/v14.15.2/node-v14.15.2-linux-x64.tar.xz | tar xJ --directory /layers/google.nodejs.runtime/node --strip-components=1"
Done "bash -c curl --fail --show-error --silent --location --retry..." (2.980257098s)
=== Node.js - NPM (google.nodejs.npm@0.9.0) ===
Installing application dependencies.
--------------------------------------------------------------------------------
Running "npm ci --quiet (NODE_ENV=production)"

> @tensorflow/tfjs-node@1.4.0 install /workspace/node_modules/@tensorflow/tfjs-node
> node scripts/install.js

CPU-linux-1.4.0.tar.gz
* Downloading libtensorflow

* Building TensorFlow Node.js bindings
node-pre-gyp install failed with error: Error: Command failed: node-pre-gyp install --fallback-to-build
node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://storage.googleapis.com/tf-builds/pre-built-binary/napi-v5/1.4.0/CPU-linux-1.4.0.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for @tensorflow/tfjs-node@1.4.0 and node@14.15.2 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
gyp ERR! find Python 
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python 
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python 
gyp ERR! configure error 
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (/layers/google.nodejs.runtime/node/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (/layers/google.nodejs.runtime/node/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (/layers/google.nodejs.runtime/node/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
gyp ERR! stack     at PythonFinder.execFileCallback (/layers/google.nodejs.runtime/node/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:315:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:327:5)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:465:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
gyp ERR! System Linux 5.4.0-1029-gcp
gyp ERR! command "/layers/google.nodejs.runtime/node/bin/node" "/layers/google.nodejs.runtime/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/workspace/node_modules/@tensorflow/tfjs-node/lib/napi-v5/tfjs_binding.node" "--module_name=tfjs_binding" "--module_path=/workspace/node_modules/@tensorflow/tfjs-node/lib/napi-v5" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=5" "--node_napi_label=napi-v5"
gyp ERR! cwd /workspace/node_modules/@tensorflow/tfjs-node
gyp ERR! node -v v14.15.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/layers/google.nodejs.runtime/node/bin/node /layers/google.nodejs.runtime/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/workspace/node_modules/@tensorflow/tfjs-node/lib/napi-v5/tfjs_binding.node --module_name=tfjs_binding --module_path=/workspace/node_modules/@tensorflow/tfjs-node/lib/napi-v5 --napi_version=7 --node_abi_napi=napi --napi_build_version=5 --node_napi_label=napi-v5' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/workspace/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1048:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
node-pre-gyp ERR! System Linux 5.4.0-1029-gcp
node-pre-gyp ERR! command "/layers/google.nodejs.runtime/node/bin/node" "/workspace/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /workspace/node_modules/@tensorflow/tfjs-node
node-pre-gyp ERR! node -v v14.15.2
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok 

added 149 packages in 7.348s
Done "npm ci --quiet (NODE_ENV=production)" (7.908008794s)
=== Utils - Label Image (google.utils.label@0.0.1) ===
```

Full logs: https://gist.github.com/ahmetb/1be3137c8a8be45169f04ebb021cbb83

**Comment by ahmetb** [comment] 2020-12-16 20:43
This might be a false alarm.

I get the same errors **without pack**, by using a Dockerfile, but `npm install` succeeds.

Closing for now.

**Comment by lukasberger** [comment] 2020-12-16 22:54
Is this a duplicate of https://github.com/GoogleCloudPlatform/buildpacks/issues/94?

**Comment by ahmetb** [comment] 2020-12-16 23:25
@lukasberger yes.
cc: @steren

From my experimentation, the problem is with node-gyp or TFJS. You have to have Python in the build env to be able to `npm install` the tfjs package.

I ended up writing a Dockerfile to workaround the problem, but I opened an issue https://github.com/tensorflow/tfjs/issues/4419 because the build should not succeed.

**Comment by matthewrobertson** [comment] 2021-10-15 22:10
I believe this was fixed by https://github.com/GoogleCloudPlatform/buildpacks/commit/7360bf9e55a60a63a8707476512be2b0912a7921

**Closed by matthewrobertson** 2021-10-15 22:10 UTC
Labels: kind/bug, lang/nodejs
