### ISSUE TITLE
Cloud Build fails for python Google Function (functions-framework)

### ISSUE THREAD

**Issue by jameslittle** [GoogleCloudPlatform/buildpacks#140] opened 2021-06-25 15:38 UTC
When using `GOOGLE_FUNCTION_TARGET`, the build works okay locally. Example below:
`pack --verbose build <FUNC_NAME> --clear-cache --builder gcr.io/buildpacks/builder:v1 --env GOOGLE_FUNCTION_TARGET=<FUNC_NAME>`

But when I trigger this in Cloud Build in GCP, it fails (with a permissions error) when trying to precompile the python code. Snippet below; full build log is attached. Kind of looks like it's failing when trying to create __pycache__ directories, but since I can't reproduce locally, it's difficult to troubleshoot. Relevant code seems to be in cmd/python/functions_framework/main.go

Builds for regular python web apps (Flask/gunicorn) don't seem to do this compile step.

```
=== Python - Functions Framework (google.python.functions-framework@0.9.5) ===
--------------------------------------------------------------------------------
Running "python3 -m compileall -f -q ."
*** Error compiling './cloud_apps/costpricer_web_api.py'...
PermissionError: [Errno 13] Permission denied: './cloud_apps/__pycache__'
*** Error compiling './cloud_apps/functions.py'...
PermissionError: [Errno 13] Permission denied: './cloud_apps/__pycache__'
Done "python3 -m compileall -f -q ." (110.672077ms)
```

[build.log](https://github.com/GoogleCloudPlatform/buildpacks/files/6717287/build.log)

**Comment by di** [comment] 2021-06-25 15:56
A few things to try:
* Can you check the permissions on these directories locally? `ls -ld cloud_apps` and `ls -ld cloud_apps/__pycache__`
* Can you try removing the `__pycache__` directory locally before submitting the build? 

Could you also give us some more details about how you're submitting the build? What platform you're on, etc. Are you invoking `gcloud builds submit` locally, pushing this to a source repository, etc?

**Comment by jameslittle** [comment] 2021-06-25 16:16
Hi @di 

The build is automatically triggered on push to git branch (code is in Cloud Source Repos). The `__pycache__` dirs definitely don't exist in the repo; have double checked this.

**Comment by di** [comment] 2021-06-25 16:33
But `cloud_apps` does? What are the permissions on that directory?

**Comment by jameslittle** [comment] 2021-06-25 17:33
AFAIK there's no way of setting permissions on a directory in a git repo. Git tracks the executable-bit on _files_ only. 
The command below just ends up showing the perms on the files under that dir, and they're 644.

I would imagine on Linux, the directories end up inheriting permissions from the system's (or user's) umask.

```
λ git ls-files -s cloud_apps
100644 7341dbad696158535a179ca99b4e97268a654100 0       cloud_apps/costpricer_web_api.py
100644 86a2327b3f8f3f32af19e1441b88220cc2cfdbad 0       cloud_apps/functions.py
```

**Comment by di** [comment] 2021-06-26 01:50
I tried to reproduce this with the following and couldn't ([output here](https://gist.github.com/di/3c998efc64dece41c0e570b41561845b)):

```
$ tree
.
├── cloud_apps
│   ├── costpricer_web_api.py
│   └── functions.py
├── cloudbuild.yaml
└── main.py

1 directory, 4 files
```
```
$ cat cloudbuild.yaml
steps:
  - name: 'gcr.io/k8s-skaffold/pack'
    args: ["pack", "--verbose", "build", "hello", "--clear-cache", "--builder", "gcr.io/buildpacks/builder:v1", "--env", "GOOGLE_FUNCTION_TARGET=hello"]
 ```
 ```
$ cat main.py
 from cloud_apps import *


def hello(request):
    return "hi"
 ```

Is there anything different about how you're invoking `pack` here? Are you able to produce a minimally reproducing example so we can debug?

**Comment by jameslittle** [comment] 2021-06-26 08:55
I think to reproduce you'd have to setup a build that is triggered remotely in GCP by git branch pushes, or tag creations. 
This is part of the workflow if you setup a Cloud Run instance with Continuous Deployment (which is what I've done).

I've attached another build log where you can see it doing the git fetch at the top. I suspect there's a change of user, between doing the fetch and running the pack build. As a workaround I've stopped using `GOOGLE_FUNCTION_TARGET` and instead I set  `GOOGLE_ENTRYPOINT ` to `functions-framework --target <function_name>` , and I guess that bypasses the problematic step.

[log-47925515-3692-42f9-bd22-0bcfd2bb1cf3.txt](https://github.com/GoogleCloudPlatform/buildpacks/files/6719853/log-47925515-3692-42f9-bd22-0bcfd2bb1cf3.txt)

**Comment by di** [comment] 2021-06-29 16:09
Ok, so it looks like you followed https://cloud.google.com/run/docs/continuous-deployment-with-cloud-build#new-service then, is that right?

I followed this guide, using Cloud Source Repositories for the provider and Cloud Buildpacks for the build type. It created the following Cloud Build configuration:

```yaml
steps:
  - name: gcr.io/k8s-skaffold/pack
    args:
      - build
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - '--builder=gcr.io/buildpacks/builder:v1'
      - '--path=.'
    id: Buildpack
    entrypoint: pack
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _LABELS: gcb-trigger-id=b6debbf6-c677-4a8e-acb1-c5f1cd6991e6
  _TRIGGER_ID: b6debbf6-c677-4a8e-acb1-c5f1cd6991e6
  _GCR_HOSTNAME: us.gcr.io
  _PLATFORM: managed
  _SERVICE_NAME: test-buildpacks
  _DEPLOY_REGION: us-central1
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - test-buildpacks
```

And then I added this:

```diff
  - name: gcr.io/k8s-skaffold/pack
    args:
      - build
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - '--builder=gcr.io/buildpacks/builder:v1'
      - '--path=.'
+      - '--env'
+      - GOOGLE_FUNCTION_TARGET=hello
    id: Buildpack
    entrypoint: pack
```

And the build succeeded with the above example.

Can you provide us with the inline build configuration you're using? You can find this by going to https://console.cloud.google.com/run -> your service name -> "Edit continuous deployment" -> "Configuration" -> "Open editor"

**Comment by di** [comment] 2021-07-01 17:02
Hi @jameslittle, are you able to share the inline build configuration that was generated for your service?

**Comment by briandealwis** [comment] 2021-07-04 12:08
@jameslittle are you able to attach your cloud build configuration?

**Comment by jameslittle** [comment] 2021-07-04 15:28
Hi @di & @briandealwis 

Please see my build config below. Looks very similar to yours; the only meaningful difference I can see is that I have a subdirectory `src` as the root of the buildpack project. But this works fine for other Cloud Run instances (non `GOOGLE_FUNCTION_TARGET` instances)

```steps:
  - name: gcr.io/k8s-skaffold/pack
    args:
      - build
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - '--builder=gcr.io/buildpacks/builder:v1'
      - '--path=src'
      - '--env'
      - GOOGLE_FUNCTION_TARGET=persist_datamodel
    id: Buildpack
    entrypoint: pack
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - '--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _SERVICE_NAME: perfectpanda-uat-datamodel-persist
  _LABELS: gcb-trigger-id=6efcdf34-9d46-4d70-b397-bff52badf935
  _TRIGGER_ID: 6efcdf34-9d46-4d70-b397-bff52badf935
  _DEPLOY_REGION: europe-west2
  _GCR_HOSTNAME: eu.gcr.io
  _PLATFORM: managed
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - perfectpanda-uat-datamodel-persist
```

**Comment by jameslittle** [comment] 2021-07-05 09:58
Also, in your source code repo, do you some code (python modules/packages) in subdirectories? As it seems to fail creating __pycache__ in subdirs.

**Comment by briandealwis** [comment] 2021-07-06 15:16
Hi @jameslittle: this is baffling. Could you provide a layout of your project so that we can try to reproduce exactly what you're seeing?

Could you add a build step prior to running pack to output the directory permissions?  That will help identify if the permission issues are happening as part of the checkout.  Something like:
```yaml
  - name: 'bash'
    args: ['find', '-L', '.', '-type', 'd', '-exec', 'ls', '-ld', '{}', ';']
```

Do you get the same _permission denied_ errors if you try to submit a build with `gcloud builds submit`?  You'll need to copy out that build script to a `cloudbuild.yaml` and remove the `substitutions` and instead provide them on the command-line.  Something like the following should work:

    gcloud builds submit --project petproactive-analytics --substitutions=_GCR_HOSTNAME=eu.gcr.io,REPO_NAME=analytics,_SERVICE_NAME=perfectpanda-uat-datamodel-persist,_DEPLOY_REGION=europe-west2,COMMIT_SHA=xxx .

One odd thing: when I try to reproduce this, even the exact version of `gcr.io/buildpacks/builder@sha256:19052a50a854df61dcb1be84101929b6a03f2404a4
1c3852c5c3998406465792` as in your build logs, I have a warning that appears:
```
Step #0 - "Buildpack": [builder] Running "python3 -m compileall -f -q ."
Step #0 - "Buildpack": [builder] Done "python3 -m compileall -f -q ." (50.328408ms)
Step #0 - "Buildpack": [builder] Handling functions with dependency on functions-framework.
Step #0 - "Buildpack": [builder] WARNING: Launch layer is setting default=true, but that is not supported until API version 0.6. This setting will be ignored.
Step #0 - "Buildpack": [builder] Warning: Warning: default processes aren't supported in this buildpack api version. Overriding the default value to false for the following processes: [web]
```

which isn't present in your build logs.

**Comment by briandealwis** [comment] 2021-07-14 15:22
Quick ping @jameslittle: even just this would help
> Could you provide a layout of your project so that we can try to reproduce exactly what you're seeing?

**Comment by matthewrobertson** [comment] 2021-11-18 20:24
I am closing this as we don't have enough information to debug. @jameslittle please re-open if you are still having issues.

**Closed by matthewrobertson** 2021-11-18 20:24 UTC
Labels: triage/needs-reproduction
